# Source the tmux config with <prefix>r
bind r source-file ~/.tmux.conf

# Get proper colors to work 
set -g default-terminal "tmux-256color"
set -ag terminal-overrides "tmux-256color"

# Allow escape sequences to go through
set -g allow-passthrough on

# Set <prefix> to Ctrl-s
set -g prefix C-s

# Enable the mouse
set -g mouse on

# Control windows and panes with vim keys
set-window-option -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Split panes with = and -
# <prefix>= | horizontaly
# <prefix>- | vertically
bind = split-window -h
bind - split-window -v

# Remove old window split keybinds
unbind '"'
unbind %

# Do not rename windows automatically
set-option -g allow-rename off

# Set the starting window index to 1
set -g base-index 1

# Move the status bar to the top of the screen
set-option -g status-position top

# Change the color of the status bar
set -g status-style bg=blue
